apply plugin: 'com.android.application'
android {
    compileSdkVersion 35
    defaultConfig {
        applicationId "com.quanglewangle.shoppingBeta"
        minSdkVersion 23
        targetSdkVersion 35
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    productFlavors {
    }
    namespace 'com.quanglewangle.peter.shoppingBeta'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
dependencies {
    api files('libs/okhttp-3.8.1.jar')
    api files('libs/okio-1.13.0.jar')
    api 'com.android.support:appcompat-v7:+'
}
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}
